In [1]:
import pandas as pd
import json

In [2]:
base_string_one = 'Data/StreamingHistory_music_'
base_string_two = '.json'
df_list = []
for i in range(0,6):
    new_string = base_string_one+str(i)+base_string_two
    print(new_string)
    current_df = pd.read_json(new_string)
    df_list.append(current_df)

combined_df = pd.concat(df_list, ignore_index=True)
combined_df

Data/StreamingHistory_music_0.json
Data/StreamingHistory_music_1.json
Data/StreamingHistory_music_2.json
Data/StreamingHistory_music_3.json
Data/StreamingHistory_music_4.json
Data/StreamingHistory_music_5.json

                endTime        artistName            trackName  msPlayed
0      2025-01-11 00:27    Kendrick Lamar          Not Like Us     93019
1      2025-01-11 16:27             Tempo       Happy Birthday     60487
2      2025-01-11 16:28      Marc Anthony        Vivir Mi Vida     79180
3      2025-01-11 16:30    Rauw Alejandro           Todo De Ti     99079
4      2025-01-11 16:33  Cali Y El Dandee  Por Fin Te Encontré    165326
...                 ...               ...                  ...       ...
49977  2026-01-10 19:51               BCA  Se Descargo el Amor    192929
49978  2026-01-10 19:53       MC Sencillo      Cara de Santita    145580
49979  2026-01-10 21:17        El Roockie                Atrás    211954
49980  2026-01-10 23:48        El Roockie                Atrás     35526
49981  2026-01-10 23:53      Real Phantom     Plena Monstruosa    274051

[49982 rows x 4 columns]

In [3]:
combined_df

                endTime        artistName            trackName  msPlayed
0      2025-01-11 00:27    Kendrick Lamar          Not Like Us     93019
1      2025-01-11 16:27             Tempo       Happy Birthday     60487
2      2025-01-11 16:28      Marc Anthony        Vivir Mi Vida     79180
3      2025-01-11 16:30    Rauw Alejandro           Todo De Ti     99079
4      2025-01-11 16:33  Cali Y El Dandee  Por Fin Te Encontré    165326
...                 ...               ...                  ...       ...
49977  2026-01-10 19:51               BCA  Se Descargo el Amor    192929
49978  2026-01-10 19:53       MC Sencillo      Cara de Santita    145580
49979  2026-01-10 21:17        El Roockie                Atrás    211954
49980  2026-01-10 23:48        El Roockie                Atrás     35526
49981  2026-01-10 23:53      Real Phantom     Plena Monstruosa    274051

[49982 rows x 4 columns]

In [8]:
combined_df['endTime'][0].split(" ")

['2025-01-11', '00:27']

In [11]:
combined_df[['Date','International Time']] = combined_df['endTime'].str.split(" ",expand = True)
combined_df

,endTime,artistName,trackName,msPlayed,Date,International Time
0,2025-01-11 00:27,Kendrick Lamar,Not Like Us,93019,2025-01-11,00:27
1,2025-01-11 16:27,Tempo,Happy Birthday,60487,2025-01-11,16:27
2,2025-01-11 16:28,Marc Anthony,Vivir Mi Vida,79180,2025-01-11,16:28
3,2025-01-11 16:30,Rauw Alejandro,Todo De Ti,99079,2025-01-11,16:30
4,2025-01-11 16:33,Cali Y El Dandee,Por Fin Te Encontré,165326,2025-01-11,16:33
...,...,...,...,...,...,...
49977,2026-01-10 19:51,BCA,Se Descargo el Amor,192929,2026-01-10,19:51
49978,2026-01-10 19:53,MC Sencillo,Cara de Santita,145580,2026-01-10,19:53
49979,2026-01-10 21:17,El Roockie,Atrás,211954,2026-01-10,21:17
49980,2026-01-10 23:48,El Roockie,Atrás,35526,2026-01-10,23:48
49981,2026-01-10 23:53,Real Phantom,Plena Monstruosa,274051,2026-01-10,23:53

In [12]:
combined_df['Date'][0].split("-")

['2025', '01', '11']

In [13]:
combined_df[['Year','Month','Day']] = combined_df['Date'].str.split("-",expand = True)
combined_df

,endTime,artistName,trackName,msPlayed,Date,International Time,Year,Month,Day
0,2025-01-11 00:27,Kendrick Lamar,Not Like Us,93019,2025-01-11,00:27,2025,01,11
1,2025-01-11 16:27,Tempo,Happy Birthday,60487,2025-01-11,16:27,2025,01,11
2,2025-01-11 16:28,Marc Anthony,Vivir Mi Vida,79180,2025-01-11,16:28,2025,01,11
3,2025-01-11 16:30,Rauw Alejandro,Todo De Ti,99079,2025-01-11,16:30,2025,01,11
4,2025-01-11 16:33,Cali Y El Dandee,Por Fin Te Encontré,165326,2025-01-11,16:33,2025,01,11
...,...,...,...,...,...,...,...,...,...
49977,2026-01-10 19:51,BCA,Se Descargo el Amor,192929,2026-01-10,19:51,2026,01,10
49978,2026-01-10 19:53,MC Sencillo,Cara de Santita,145580,2026-01-10,19:53,2026,01,10
49979,2026-01-10 21:17,El Roockie,Atrás,211954,2026-01-10,21:17,2026,01,10
49980,2026-01-10 23:48,El Roockie,Atrás,35526,2026-01-10,23:48,2026,01,10
49981,2026-01-10 23:53,Real Phantom,Plena Monstruosa,274051,2026-01-10,23:53,2026,01,10

In [15]:
import kagglehub
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [16]:
# Download latest version
path = kagglehub.dataset_download("melissamonfared/spotify-tracks-attributes-and-popularity")

print("Path to dataset files:", path)

# Now just use that path to load your data
df = pd.read_csv(f"{path}\dataset.csv")

<>:7: SyntaxWarning: invalid escape sequence '\d'
<>:7: SyntaxWarning: invalid escape sequence '\d'
C:\Users\moffa\AppData\Local\Temp\ipykernel_25732\234194689.py:7: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_csv(f"{path}\dataset.csv")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.11), please consider upgrading to the latest version (0.4.1).
Path to dataset files: C:\Users\moffa\.cache\kagglehub\datasets\melissamonfared\spotify-tracks-attributes-and-popularity\versions\1

In [17]:
df

,index,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [20]:
df_merged = pd.merge(combined_df, df, left_on='artistName', right_on = 'artists')
df_merged

,endTime,artistName,trackName,msPlayed,Date,International Time,Year,Month,Day,index,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,2025-01-11 00:27,Kendrick Lamar,Not Like Us,93019,2025-01-11,00:27,2025,01,11,51500,...,-6.638,0,0.1020,0.000282,0.000054,0.0958,0.421,150.011,4,hip-hop
1,2025-01-11 00:27,Kendrick Lamar,Not Like Us,93019,2025-01-11,00:27,2025,01,11,51650,...,-5.527,1,0.1050,0.377000,0.000002,0.1190,0.408,139.956,4,hip-hop
2,2025-01-11 16:28,Marc Anthony,Vivir Mi Vida,79180,2025-01-11,16:28,2025,01,11,67426,...,-3.979,0,0.1150,0.633000,0.000000,0.1600,0.671,91.090,4,latin
3,2025-01-11 16:28,Marc Anthony,Vivir Mi Vida,79180,2025-01-11,16:28,2025,01,11,67428,...,-6.099,0,0.0372,0.654000,0.000000,0.1040,0.901,93.295,4,latin
4,2025-01-11 16:28,Marc Anthony,Vivir Mi Vida,79180,2025-01-11,16:28,2025,01,11,67430,...,-3.129,1,0.0868,0.546000,0.000000,0.1390,0.891,177.086,4,latin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
713931,2026-01-10 18:40,Daddy Yankee,ABCD,20836,2026-01-10,18:40,2026,01,10,89768,...,-4.228,0,0.2920,0.076000,0.000000,0.0631,0.873,88.007,4,reggaeton
713932,2026-01-10 18:40,Daddy Yankee,ABCD,20836,2026-01-10,18:40,2026,01,10,89775,...,-2.814,1,0.0357,0.047800,0.000000,0.1200,0.708,93.979,4,reggaeton
713933,2026-01-10 18:40,Daddy Yankee,ABCD,20836,2026-01-10,18:40,2026,01,10,89776,...,-5.155,1,0.0859,0.072700,0.000003,0.0631,0.533,176.061,4,reggaeton
713934,2026-01-10 18:40,Daddy Yankee,ABCD,20836,2026-01-10,18:40,2026,01,10,89778,...,-3.170,0,0.0987,0.061300,0.004030,0.0327,0.842,89.988,4,reggaeton
713935,2026-01-10 18:40,Daddy Yankee,ABCD,20836,2026-01-10,18:40,2026,01,10,89975,...,-3.604,0,0.0428,0.069000,0.000064,0.7560,0.663,100.025,4,reggaeton

In [21]:
df_no_dupes = df_merged.drop_duplicates(subset='trackName')
df_no_dupes

,endTime,artistName,trackName,msPlayed,Date,International Time,Year,Month,Day,index,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,2025-01-11 00:27,Kendrick Lamar,Not Like Us,93019,2025-01-11,00:27,2025,01,11,51500,...,-6.638,0,0.1020,0.000282,0.000054,0.0958,0.421,150.011,4,hip-hop
2,2025-01-11 16:28,Marc Anthony,Vivir Mi Vida,79180,2025-01-11,16:28,2025,01,11,67426,...,-3.979,0,0.1150,0.633000,0.000000,0.1600,0.671,91.090,4,latin
34,2025-01-11 16:30,Rauw Alejandro,Todo De Ti,99079,2025-01-11,16:30,2025,01,11,68605,...,-3.605,0,0.0506,0.310000,0.000163,0.0932,0.342,127.949,4,latino
37,2025-01-11 16:33,Cali Y El Dandee,Por Fin Te Encontré,165326,2025-01-11,16:33,2025,01,11,31646,...,-4.477,0,0.0810,0.018300,0.000000,0.0727,0.782,172.068,4,electro
47,2025-01-11 16:41,Sebastian Yatra,Vagabundo,108855,2025-01-11,16:41,2025,01,11,88319,...,-4.976,1,0.0485,0.138000,0.000000,0.1050,0.630,91.006,4,reggae
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711800,2026-01-09 23:07,Becky G,VÁMONOS,134020,2026-01-09,23:07,2026,01,09,20453,...,-7.548,1,0.0487,0.031700,0.000036,0.2850,0.121,119.987,4,dance
712558,2026-01-10 15:24,Thousand Foot Krutch,Courtesy Call - Reignited,8463,2026-01-10,15:24,2026,01,10,2058,...,-5.145,0,0.0809,0.004090,0.000000,0.0822,0.445,164.079,4,alt-rock
713018,2026-01-11 16:41,Andrew Ripp,Loves Got a Way,1600,2026-01-11,16:41,2026,01,11,770,...,-6.952,1,0.0288,0.877000,0.000000,0.1200,0.395,104.959,4,acoustic
713023,2026-01-11 16:43,TobyMac,Speak Life,4224,2026-01-11,16:43,2026,01,11,2390,...,-6.537,1,0.0298,0.090800,0.000015,0.0470,0.329,124.980,4,alt-rock
713025,2026-01-11 18:04,Eddie Santiago,Lluvia,6066,2026-01-11,18:04,2026,01,11,95015,...,-4.857,0,0.0359,0.397000,0.000053,0.0834,0.802,165.094,4,salsa

In [22]:
#type(df_no_dupes['msPlayed'][0])

numpy.int64

In [24]:
df_no_dupes = df_no_dupes[df_no_dupes['msPlayed'] > 10000]
df_no_dupes

,endTime,artistName,trackName,msPlayed,Date,International Time,Year,Month,Day,index,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,2025-01-11 00:27,Kendrick Lamar,Not Like Us,93019,2025-01-11,00:27,2025,01,11,51500,...,-6.638,0,0.1020,0.000282,0.000054,0.0958,0.421,150.011,4,hip-hop
2,2025-01-11 16:28,Marc Anthony,Vivir Mi Vida,79180,2025-01-11,16:28,2025,01,11,67426,...,-3.979,0,0.1150,0.633000,0.000000,0.1600,0.671,91.090,4,latin
34,2025-01-11 16:30,Rauw Alejandro,Todo De Ti,99079,2025-01-11,16:30,2025,01,11,68605,...,-3.605,0,0.0506,0.310000,0.000163,0.0932,0.342,127.949,4,latino
37,2025-01-11 16:33,Cali Y El Dandee,Por Fin Te Encontré,165326,2025-01-11,16:33,2025,01,11,31646,...,-4.477,0,0.0810,0.018300,0.000000,0.0727,0.782,172.068,4,electro
47,2025-01-11 16:41,Sebastian Yatra,Vagabundo,108855,2025-01-11,16:41,2025,01,11,88319,...,-4.976,1,0.0485,0.138000,0.000000,0.1050,0.630,91.006,4,reggae
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709061,2026-01-08 14:19,El Gran Combo De Puerto Rico,Me Liberé,241927,2026-01-08,14:19,2026,01,08,95342,...,-7.240,0,0.0323,0.712000,0.000000,0.1960,0.963,98.913,4,salsa
709298,2026-01-08 20:41,Becky G,Todo Cambio (feat. CNCO),158425,2026-01-08,20:41,2026,01,08,20453,...,-7.548,1,0.0487,0.031700,0.000036,0.2850,0.121,119.987,4,dance
711058,2026-01-09 16:03,Bruno Mars,I Just Might,212974,2026-01-09,16:03,2026,01,09,20072,...,-6.826,1,0.0516,0.337000,0.000000,0.0820,0.468,150.014,4,dance
711781,2026-01-09 21:31,Becky G,TAJIN,174540,2026-01-09,21:31,2026,01,09,20453,...,-7.548,1,0.0487,0.031700,0.000036,0.2850,0.121,119.987,4,dance
711800,2026-01-09 23:07,Becky G,VÁMONOS,134020,2026-01-09,23:07,2026,01,09,20453,...,-7.548,1,0.0487,0.031700,0.000036,0.2850,0.121,119.987,4,dance

In [ ]:
with open('Data/YourLibrary.json','r', encoding='utf-8') as f:
    data = json.load(f)
keylist = list(data.keys())
print(keylist)

In [ ]:
"""
dataframes = []

for i in range(5):
    df = pd.DataFrame({
        'id': range(i*10, (i+1)*10),
        'value': range(100+i*10, 100+(i+1)*10),
        'group': [f'Group_{i}'] * 10
    })
    dataframes.append(df)
"""

In [ ]:
for i in keylist:
    print(i)
    try:
        print(data[i][0].keys())
    except IndexError:
        print(f"Index {i} is out of range, skipping...")
        continue  # Skip to next iteration
        print(f"Processing complete for index {i}")

In [ ]:
data['tracks'][0]

In [ ]:
df = pd.DataFrame(columns=data['tracks'][0].keys())
df

In [ ]:
tracksdf = pd.concat([df, pd.DataFrame(data['tracks'])], ignore_index = True)
tracksdf

In [ ]:
data['albums'][0].keys()

In [ ]:
albumsdf = pd.DataFrame(columns=data['albums'][0].keys())
albumsdf

In [ ]:
albumsdf = pd.concat([albumsdf, pd.DataFrame(data['albums'])], ignore_index = True)
albumsdf

In [ ]:
with open('Data/Wrapped2024.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
data

In [ ]:
data.keys()

In [ ]:
data['topArtists'].keys()

In [ ]:
data['topArtists']

In [ ]:
data['topArtists'].keys()

In [ ]:
pd.DataFrame(data['topArtists']) #Add the date columns

In [ ]:
data['topPodcasts'].keys()

In [ ]:
data['topPodcasts']

In [ ]:
df = pd.DataFrame(columns=data['topPodcasts'].keys())
df

In [ ]:
df.loc[len(df)] = data['topPodcasts']
df

In [ ]:
data['yearlyMetrics']

In [ ]:
df = pd.DataFrame(columns=data['yearlyMetrics'].keys())
df

In [ ]:
df.loc[len(df)] = data['yearlyMetrics']
df

In [ ]:
data['musicEvolution'].keys()

In [ ]:
data['musicEvolution']['eras'][0].keys()

In [ ]:
df = pd.DataFrame(columns=data['musicEvolution']['eras'][0].keys())
df

In [ ]:
evoldf = pd.concat([df, pd.DataFrame(data['musicEvolution']['eras'])], ignore_index = True)
evoldf # Can explode the pivotalArtists column, and the tracks column in PySpark

In [ ]:
with open('Data/StreamingHistory_podcast_0.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
#data

In [ ]:
data[0].keys()

In [ ]:
podcastsdf = pd.DataFrame(columns=data[0].keys())
podcastsdf

In [ ]:
podcastsdf = pd.concat([podcastsdf, pd.DataFrame(data)], ignore_index = True)
podcastsdf